server:
  port : 8181
  
spring:

  application:
    name: URL_SHORTNER

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    
  h2:
    console:
      enabled: true
      path : /db
